apiVersion: v1
kind: Secret
metadata:
  name: apphoster-secrets
stringData:
  DATABASE_URL: "postgres://postgres:postgres@postgres:5432/apphoster"
  aws_access_key_id: "PLACEHOLDER_KEY"
  aws_secret_access_key: "PLACEHOLDER_SECRET"
  aws_s3_bucket: "PLACEHOLDER_BUCKET"
